@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzExNTR9.AVdQ2tUAjGIi5t1WKkgnC_SmOIjaya0Ak76jZ0QVs-I


### Index request
GET http://localhost:3000/products.json
Authorization: Bearer {{jwt}}

### Show request
GET http://localhost:3000/products/2.json
Authorization: Bearer {{jwt}}

### POST request (create new product)
POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "stuff",
  "price": 100,
  "description": "some random stuff",
  "supplier_id": 2
}

### Patch (update) request
PATCH http://localhost:3000/products/10.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  
}

### Destroy request (delete product)
DELETE http://localhost:3000/products/6
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Victoria",
  "email": "vicky@example.com",
  "password": "purple",
  "password_confirmation": "purple"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

# {
#   "email": "erwin@example.com",
#   "password": "password"
# }
{
  "email": "vicky@example.com",
  "password": "purple"
}

### Order index
GET http://localhost:3000/orders
Authorization: Bearer {{jwt}}
### Order show
GET http://localhost:3000/orders/1
Authorization: Bearer {{jwt}}
### Order create
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "user_id": 1,
  "product_id": 1,
  "quantity": 10,
  "subtotal": 1000,
  "tax": 90,
  "total": 1090
}

### Carted Products index for current user
GET http://localhost:3000/carted_products
Authorization: Bearer {{jwt}}

### Carted Products create
POST http://localhost:3000/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 1,
  "quantity": 2
}