### Index request
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDc5NzE3Nzh9.1VUWZGPENVopAcsJawQ1xBPDy-mVuEicLKGm3L0gLdg

### Show request
GET http://localhost:3000/products/2.json

### POST request (create new product)
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "xbox 51",
  "price": 1000,
  "url": ["xbox.com"],
  "description": "51st kind of this gaming console",
  "supplier_id": 1
}

### Patch (update) request
PATCH http://localhost:3000/products/10.json
Content-Type: application/json

{
  
}

### Destroy request (delete product)
DELETE http://localhost:3000/products/6
Content-Type: application/json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Victoria",
  "email": "vicky@example.com",
  "password": "purple",
  "password_confirmation": "purple"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "erwin@example.com",
  "password": "password"
}

### Order index
GET http://localhost:3000/orders

### Order show
GET http://localhost:3000/orders/1

### Order create
POST http://localhost:3000/orders
Content-Type: application/json

{
  "user_id": 1,
  "product_id": 1,
  "quantity": 10,
  "subtotal": 1000,
  "tax": 90,
  "total": 1090
}